# Set verbose console logging.
debug/verbose: true

# Server configuration.
server:
  # HTTP port
  listen: 7004

  # Main control file
  index: control/index.yaml

  # This is the file that will store persistence for
  # your application.
  persist: data/persist.yaml

  # These directories will be shared under:
  #   http://localhost/files/*
  dirs:
    - control
    - preset
    - shader
    - image
    - data
